### ISSUE TITLE
BareMetalHost doesn't reconcile when a Machine config is specified with the BMH as the providerID

### ISSUE THREAD

**Issue by abhat** [openshift/cluster-api-provider-baremetal#120]
If a BMH CR is in Ready state and this is followed by creating a Machine CR that points to the BMH CR instance (using the ProviderID and the annotation of the BMH), the BMH CR doesn't get reconciled correctly to go from `Ready` to `Provisioned` state. Instead it stays in the "Ready" state and the machine provisioning fails.

I was expecting that the annotation and the provider ID link the BMH to the machine and in the next reconciliation loop of the BMH CR, the BMH should have provisioned correctly and the machine reconciliation should have said "Provisioning" and the corresponding node should have eventually gotten created.

Example:

Create a BMH:

```
cat <<EOF | oc apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: ostest-master-3-bmc-secret
  namespace: openshift-machine-api
type: Opaque
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQ=
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: ostest-master-3
  namespace: openshift-machine-api
spec:
  online: true
  bootMACAddress: 00:a3:19:55:91:56
  bmc:
    address: redfish+http://192.168.111.1:8000/redfish/v1/Systems/fec49389-ffb7-4c53-91ef-673a548c03b2
    credentialsName: ostest-master-3-bmc-secret
EOF
```
BMH will go into Ready state assuming the virsh xml is valid and the bootMacAddress and the bmcAddress are correct.

Now create a machine CR
```
cat <<EOF | oc apply -f -
apiVersion: machine.openshift.io/v1beta1
kind: Machine
metadata:
  annotations: 
    metal3.io/BareMetalHost: openshift-machine-api/ostest-master-3
  labels:
    machine.openshift.io/cluster-api-cluster: ostest-pbcnb
    machine.openshift.io/cluster-api-machine-role: master
    machine.openshift.io/cluster-api-machine-type: master
  name: ostest-pbcnb-master-3
  namespace: openshift-machine-api
spec:
  providerID: baremetalhost:///openshift-machine-api/ostest-master-3
  providerSpec:
    value:
      hostSelector: {}
      image:
        checksum: http://172.22.0.3:6180/images/rhcos-46.82.202009222340-0-openstack.x86_64.qcow2/rhcos-46.82.202009222340-0-compressed.x86_64.qcow2.md5sum
        url: http://172.22.0.3:6180/images/rhcos-46.82.202009222340-0-openstack.x86_64.qcow2/rhcos-46.82.202009222340-0-compressed.x86_64.qcow2
      userData:
        name: master-user-data
EOF
```

The Machine CR shows status as `Failed` and the BMH CR stays in `Ready` state.
